### PR TITLE
Recursive

### PR DESCRIPTION
**Pull request by c10l**
This is a rebase of https://github.com/logstash-plugins/logstash-filter-de_dot/pull/19

### CODE REVIEW

**Comment by jsvd** [comment]
hi @c10l the CLA checker is failing as the PR has a commit from Michael Lorant (email can be found in the [patch](https://patch-diff.githubusercontent.com/raw/logstash-plugins/logstash-filter-de_dot/pull/22.patch)), who we can't find a signature for

**Comment by jhuntoo** [comment]
Thanks @jsvd, I'm a colleague of @c10l and we are really interested in this functionality as we have loads of k8s labels with dots in them which cause issues on a daily basis. I have sent an email to Michael Lorant requesting his help to see if we can get this across the line.

**Comment by mikelorant** [comment]
Happy to help out and have received your email. Let me take a look at this tomorrow and help get this merged.

**Comment by jhuntoo** [comment]
Hi @mikelorant , I was wondering if you had managed to complete the Contributor Agreement form yet ?

**Comment by johnmschoonover** [comment]
Hey @mikelorant :

Was about to build my own one of these but saw you had semi-recent commits on this. Any chance of completing the above to get this code merged in?

**Comment by mikelorant** [comment]
I've signed the agreement, not sure how to force a recheck of this PR.

**Review by mikelorant — APPROVED** [review]

**Comment by johnmschoonover** [comment]
@jsvd any thoughts on moving this forward?

**Comment by johnmschoonover** [comment]
@elasticcla ?

**Comment by johnmschoonover** [comment]
or @untergeek ? Any chance of an assist here?

**Comment by untergeek** [comment]
I'm not on the Logstash team any more, but perhaps @jsvd can respond.

**Comment by mohitg81** [comment]
@jsvd Can this PR be merged with main branch as recursive option greatly helps write a simple config instead of listing all subfields individually? Or is there another plugin/method that can be used?

**Comment by jsvd** [comment]
It seems like the [original author/s of the commits](https://patch-diff.githubusercontent.com/raw/logstash-plugins/logstash-filter-de_dot/pull/22.patch) don't have the cla signed. I will take this on once it's signed, sorry for the delay here folks..

**Comment by johnmschoonover** [comment]
@jvsd he mentioned in thread above he has done this but can't kick off another re-check of the PR.

**Comment by jsvd** [comment]
>  he mentioned in thread above he has done this but can't kick off another re-check of the PR.

I have launched the recheck, that still shows as failed. The PR has two commits from two different authors. 
@mikelorant the email from your commit is not associated with your github profile, which is failing the check. Hopefuly you're still interested in helping carrying forward here :)

**Comment by mikelorant** [comment]
Will do what I can to sort this out.

I've signed it again with the exact email address as per the commit.

**Comment by mikelorant** [comment]
I've opened pull request #23 with the exact same changes however it is from my fork which allows me to force a recheck easily. That check now passes CLA, so this means if you recheck this one, it should pass. If not, consider using the new pull request.

**Review by mikelorant — APPROVED** [review]

**Comment by jsvd** [comment]
solved by #24 (with retained authorship) and published as https://rubygems.org/gems/logstash-filter-de_dot/versions/1.1.0

**Pull request closed without merging**
