### PR TITLE
Fix for issue 9 (boolean false breaks de_dot)

### PR DESCRIPTION
**Pull request by tombrown52**
This fixes issue #9 by making the existence check actually check for existence, rather than just truthiness.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @tombrown52, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-filter-de_dot/pull/11.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by tombrown52** [comment]
Sorry about that @karmi. I rewrote my commit with the proper email, and we should be good as soon as the CI is complete.

**Comment by tombrown52** [comment]
Please merge the PR or comment as to why it cannot/will not be merged. Thanks!

**Comment by untergeek** [comment]
@tombrown52 I apologize for the slow response.  One of the reasons this isn't as pressing as it could be is that the anticipated future release of Elasticsearch will allow dotted field names again.  We will still get to this when we can review it completely and respond.

**Comment by untergeek** [comment]
Please rebase this on the current master branch.  The API changes have different requirements.

**Comment by untergeek** [comment]
Also, please increment the version number and the Changelog

**Comment by jsvd** [comment]
merged in fc6018b772d470c552b202080a709f560c3cc41a

**Pull request closed without merging**
